### ISSUE TITLE
AMQPQueue routing key

### ISSUE THREAD

**Issue by leonardor** [fintech-fab/laravel-queue-rabbitmq#12]
Hi!

I work with this library for two days now and I have a problem with the queue binding from the declareQueue() and declareDelayedQueue() methods: the second argument of the bind method is explicitly the routing key however the bind is to the $name of the queue and not a routing key string (which is not the same thing as the queue name):

$queue->bind($this->exchange->getName(), $this->routing_key);

I propose that this argument should be $this->routing_key and this property would be injected in the constructor as the last argument and assign like this:

public function __construct(AMQPConnection $amqpConnection, $default_queue, $exchange_name, $exchange_type, $exchange_flags, $routing_key) {
	$this->routing_key = $routing_key;
	...
}

That implies that the return of the RabbitMQConnector connect() method would be changed to:

return new RabbitMQQueue(
	$connection,
	$config['queue'],
	$config['exchange_name'],
	$config['exchange_type'],
	$config['exchange_flags'],
	$config['routing_key']
);

**Comment by vladimir-yuldashev** [comment]
PECL extension version is not supported anymore. Take a look at a new version of our package: https://github.com/fintech-fab/laravel-queue-rabbitmq/tree/v4.2
