### ISSUE TITLE
Use of undefined constant AMQP_EX_TYPE_DIRECT - assumed 'AMQP_EX_TYPE_DIRECT'

### ISSUE THREAD

**Issue by Choandara** [fintech-fab/laravel-queue-rabbitmq#14]
ErrorException (E_UNKNOWN)

Use of undefined constant AMQP_EX_TYPE_DIRECT - assumed 'AMQP_EX_TYPE_DIRECT'

**Comment by BardiaAfshin** [comment]
I'm getting the same error

**Comment by vladimir-yuldashev** [comment]
Install pecl amqp extension
