### ISSUE TITLE
Error LaravelQueueRabbitMQ/Queue/Jobs/RabbitMQJob

### ISSUE THREAD

**Issue by giboow** [fintech-fab/laravel-queue-rabbitmq#16]
I've this error in my Laravel error log. Perhaps we can ignore message with no jobs?

    [2015-02-13 10:19:03] production.ERROR: exception 'ErrorException' with message 'Undefined index: job' in vendor/fintech-fab/laravel-queue-rabbitmq/src/FintechFab/LaravelQueueRabbitMQ/Queue/Jobs/RabbitMQJob.php:81

proposed code  :

    /**
	 * Release the job back into the queue.
	 *
	 * @param  int $delay
	 *
	 * @return void
	 */
	public function release($delay = 0)
	{
		$this->delete();

		$body = $this->envelope->getBody();
		$body = json_decode($body, true);

        if (!isset($data['job'])) {
            return;
        }

		$attempts = $this->attempts();

		// write attempts to body
		$body['data']['attempts'] = $attempts + 1;

		$job = $body['job'];
		$data = $body['data'];

		// push back to a queue
		if ($delay > 0) {
			Queue::later($delay, $job, $data, $this->getQueue());
		} else {
			Queue::push($job, $data, $this->getQueue());
		}
	}

I know it's just a patch to resolve this mistake.. I have not been able to identify the source of this.

Thanks

@Giboow

**Comment by vladimir-yuldashev** [comment]
The task has been put on to the queue not by Laravel?

**Comment by giboow** [comment]
I haven't other service who use this queue..

**Comment by vladimir-yuldashev** [comment]
We can't ignore messages with no jobs I guess.
