### ISSUE TITLE
Composer, not be found in any version.

### ISSUE THREAD

**Issue by hakanersu** [fintech-fab/laravel-queue-rabbitmq#17]
Running ```composer require "fintech-fab/laravel-queue-rabbitmq"``` pulling dev-master but you warn at documentation that not use dev-master.

When trying to pull with ```"fintech-fab/laravel-queue-rabbitmq": "5.0"``` it gives error that version not found.It seems 5.0 not presented at packagist nor tagged here yet.

I guess we have to use dev-master?

**Comment by vladimir-yuldashev** [comment]
Yes, 5.0 haven't been tested yet, you may use dev-master on your dev machine, but please do not use it on production. Also, if you will test dev-master, send us the results of everything works properly

**Comment by hakanersu** [comment]
Thank you @vladimir-yuldashev i'll report issues.
