### ISSUE TITLE
Request for more extensive error details

### ISSUE THREAD

**Issue by normk61** [fintech-fab/laravel-queue-rabbitmq#18]
When an exception occurs in the publish function, the error handler is only able to report true/false on this code:
                $job = $this->exchange->publish($payload, $queue->getName());

                if (!$job) {
                        throw new AMQPException('Could not push job to a queue');
                }

I was hoping for more details such as whether it is a connection failure, an authentication failure, a missing queue, exchange, etc.  is there any way to find the root cause of the failed publish call and make it available in the Exception message?

Laravel 4.2 version, but I noticed the 5.0 version is similar.

Thanks!!

**Comment by stephenricks** [comment]
Getting the same error.
![queue](https://cloud.githubusercontent.com/assets/6007951/6392357/d0e8756e-bdfa-11e4-96a1-ace38f627f74.JPG)

tried to listen the queue  using artisan command and gives no error. Now I am wondering where the error is occuring when I am adding a job in the queue.

**Comment by normk61** [comment]
For my case, it turned out that the connection request to the server where
Rabbit was running was failing, not because of rabbitmq credentials but
because of an lsass error due to the account that the consumer (listener)
process was running under when it was first started with artisan.  I
happened to notice this in the consumer's syslog.  The user's LDAP account
was disabled because he left the company but the process was running under
his username.  Failures can occur at many levels, connection to the rabbit
server, rabbit credentials unauthorized, queue not found, rabbit not
running, etc.  If we can get more details from this exception,, then
hopefully it will help many developers out in the future.  Thanks again for
considering this.

**Comment by normk61** [comment]
Was any action taken in the source code?

**Comment by vladimir-yuldashev** [comment]
Branch with pecl extension is deprecated now. `AMQPException` will be thrown by `videlalvaro/php-amqplib` and if it provides something you can get more info
