### ISSUE TITLE
Laravel 5.0.6

### ISSUE THREAD

**Issue by kacperkrawczyk** [fintech-fab/laravel-queue-rabbitmq#19]
Hi,

I have problem with requiring newest version with composer on clean installation of Laravel 5.0.6. As you wrote in readme I'm running this command: composer require "fintech-fab/laravel-queue-rabbitmq". After running "composer update" it tries to download 4.2 version. When I place manually "fintech-fab/laravel-queue-rabbitmq": "5.0" in composer.json then composer says that this version doesn't exist.

The only way to download latest version is to change 5.0 to dev-master. After that I have the latest version 5.0 but I have another problem. I've added 'FintechFab\LaravelQueueRabbitMQ\LaravelQueueRabbitMQServiceProvider' in providers section to my app.php. When I try to run main page I get:

ReflectionException in Container.php line 776:
Class queue does not exist
1. in Container.php line 776
2. at ReflectionClass->__construct('queue') in Container.php line 776
3. at Container->build('queue', array()) in Container.php line 656
4. at Container->make('queue', array()) in Application.php line 613
5. at Application->make('queue') in Container.php line 1231
6. at Container->offsetGet('queue') in LaravelQueueRabbitMQServiceProvider.php line 20
(...)

Could you please help me with it?

**Comment by vladimir-yuldashev** [comment]
Guys, final tests, I think release will be tomorrow and it will be without pecl extension, pure php

**Comment by vladimir-yuldashev** [comment]
RELEASED ! :) https://packagist.org/packages/fintech-fab/laravel-queue-rabbitmq

stable: 5.0
unstable: 5.0.*@dev

**Comment by martinlindhe** [comment]
wonderful! gonna give this a try asap

/m
