### ISSUE TITLE
Return faild to default connection

### ISSUE THREAD

**Issue by ivan1986** [fintech-fab/laravel-queue-rabbitmq#24]
https://github.com/fintech-fab/laravel-queue-rabbitmq/blob/v4.2/src/FintechFab/LaravelQueueRabbitMQ/Queue/Jobs/RabbitMQJob.php#L89

Queue::later($delay, $job, $data, $this->getQueue());
to
Queue::connection($connection)->later($delay, $job, $data, $this->getQueue());

and push - same

**Comment by vladimir-yuldashev** [comment]
Merged and released. Thank you.
