### ISSUE TITLE
config / flag for 'create & bind queue for exchange by default'

### ISSUE THREAD

**Issue by moominpapa** [fintech-fab/laravel-queue-rabbitmq#33]
Hi, 

would it be OK for me to add a configuration property to allow to suppress the automatic creation of a queue & bind to the exchange? 
I would really need this option to be able to e.g. use fanout exchange and bind my own queues I would like to get my messages pushed to...

**Comment by vladimir-yuldashev** [comment]
Hello,

If you will realize this feature it will be definitely useful.

**Comment by moominpapa** [comment]
Hi, I've created a pull request.
