### ISSUE TITLE
How to use Curl ?

### ISSUE THREAD

**Issue by oguzcicek** [fintech-fab/laravel-queue-rabbitmq#35]
Hello , thanks for this great package !

How can i connect a service with curl in RabbitMQ? 

I mean , i want to init a curl connection in my ```handle``` method like :

```
   $ch = curl_init($URL);
        curl_setopt($ch, CURLOPT_MUTE, 1);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: text/xml'));
        curl_setopt($ch, CURLOPT_POSTFIELDS, "$xml_data");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        $output = curl_exec($ch);
        curl_close($ch);
```

**Comment by alexw23** [comment]
Try guzzle instead

**Comment by vladimir-yuldashev** [comment]
Why do you need to connect via "curl"?

**Comment by alexw23** [comment]
I think this question is more relevant for discussion on Laravel, it's unrelated to a specific driver, and more so related to using laravel queues.

**Comment by oguzcicek** [comment]
i tired to connect a SMS service with curl.
