### ISSUE TITLE
ConnectorInterface interface specs are violated

### ISSUE THREAD

**Issue by dereckson** [fintech-fab/laravel-queue-rabbitmq#42]
Currently, the `RabbitMQConnector` class implements the `ConnectorInterface` interface.

According [the interface specification](http://laravel.com/api/5.1/Illuminate/Database/Connectors/ConnectorInterface.html), the `connect` method must return a `PDO` object, but here, `RabbitMQConnector::connect()` returns a `Queue` object.

**Comment by vladimir-yuldashev** [comment]
Hi there,

the link you provided stays for "Illuminate/Database/Connectors" not for Queue
